[build-system]
requires = ["setuptools", "wheel", "pip"]
build-backend = "setuptools.build_meta"

[tool.pip_install]
torch = { version = "2.5.1+cu124", index-url = "https://download.pytorch.org/whl/cu124" }
